export enum UserType {
  SUPERADMIN = 'SUPER_ADMIN',
  INSTITUTE_ADMIN = 'INSTITUTE_ADMIN',
  STUDENT = 'STUDENT',
  ATTEDANCEMARKER = 'ATTEDANCE_MARKER',
  TEACHER = 'TEACHER',
  PARENT = 'PARENT',
}
