export const USER_CONSTANTS = {
  VALIDATION: {
    FIRST_NAME_MIN_LENGTH: 1,
    FIRST_NAME_MAX_LENGTH: 100,
    LAST_NAME_MIN_LENGTH: 1,
    LAST_NAME_MAX_LENGTH: 100,
    PASSWORD_MIN_LENGTH: 6,
    PASSWORD_MAX_LENGTH: 255,
    PHONE_MIN_LENGTH: 10,
    PHONE_MAX_LENGTH: 20,
    NIC_MIN_LENGTH: 10,
    NIC_MAX_LENGTH: 20,
    BIRTH_CERT_MAX_LENGTH: 50,
    CITY_MAX_LENGTH: 100,
    DISTRICT_MAX_LENGTH: 100,
    PROVINCE_MAX_LENGTH: 100,
    POSTAL_CODE_MAX_LENGTH: 20,
    COUNTRY_MAX_LENGTH: 100,
    IMAGE_URL_MAX_LENGTH: 255,
  },
  PAGINATION: {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 10,
    MAX_LIMIT: 100,
  },
  SORTING: {
    DEFAULT_SORT_BY: 'createdAt',
    DEFAULT_SORT_ORDER: 'DESC' as const,
    ALLOWED_SORT_FIELDS: [
      'id',
      'firstName',
      'lastName',
      'email',
      'createdAt',
      'updatedAt',
      'userType',
      'city',
      'district',
      'province',
    ],
  },
  BCRYPT: {
    SALT_ROUNDS: 12,
  },
} as const;
